### ISSUE TITLE
Create view for upload a file

### ISSUE THREAD

**Issue by Aleup** [chrissaher/uploader#2]

**Comment by Aleup** [comment]
In the branch "Clientside", the view to upload files has been created.

![unknown](https://user-images.githubusercontent.com/3434827/86699138-8778c680-bfd5-11ea-91e1-728c4249c37b.png)

**Comment by chrissaher** [comment]
Please close the issue when it is merge on develop, so we can link the issue to a pull request.

**Comment by Aleup** [comment]
The view has been added to the branch "Develop"
